# -*- coding: utf-8 -*-
"""AMP social links

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTtdtmacACZo66FAmm94anz_9TAXuuiB
"""

from jinja2 import Template
from IPython.display import display, HTML

# 1. Data Structure defining the social networks
# Added 'profile_pattern' to show how to build the URL from user input
social_links = [
    {
        "name": "GitHub",
        "url": "https://github.com/yourusername",
        "profile_pattern": "https://github.com/{handle}",
        "handle": "yourusername",
        "icon_class": "bi bi-github",
        "bg_color": "#24292e",
        "text_color": "#ffffff",
        "border_color": "#1b1f23",
        "cta": "View Repo"
    },
    {
        "name": "YouTube",
        "url": "https://youtube.com/@YourChannel",
        "profile_pattern": "https://youtube.com/@{handle}",
        "handle": "YourChannel",
        "icon_class": "bi bi-youtube",
        "bg_color": "#ff0000",
        "text_color": "#ffffff",
        "border_color": "#cc0000",
        "cta": "Subscribe"
    },
    {
        "name": "Twitter / X",
        "url": "https://twitter.com/yourhandle",
        "profile_pattern": "https://twitter.com/{handle}",
        "handle": "yourhandle",
        "icon_class": "bi bi-twitter-x",
        "bg_color": "#000000",
        "text_color": "#ffffff",
        "border_color": "#333333",
        "cta": "Follow"
    },
    {
        "name": "LinkedIn",
        "url": "https://linkedin.com/in/your-profile",
        "profile_pattern": "https://linkedin.com/in/{handle}",
        "handle": "your-profile",
        "icon_class": "bi bi-linkedin",
        "bg_color": "#0077b5",
        "text_color": "#ffffff",
        "border_color": "#005582",
        "cta": "Connect"
    }
]

# 2. Jinja2 Template (This is what you would put in your Flask HTML template file)
template_string = """
<!-- Include Bootstrap CSS & Bootstrap Icons (If not already in your base template) -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<div class="container mt-4" style="max-width: 500px;">
    <!-- Vertical list using Bootstrap flexbox -->
    <div class="d-flex flex-column gap-3">
        {% for link in links %}
        <div class="card shadow-sm transition-all"
             style="background-color: {{ link.bg_color }};
                    border: 2px solid {{ link.border_color }};
                    color: {{ link.text_color }};
                    border-radius: 15px;">
            <div class="card-body d-flex align-items-center justify-content-between">

                <!-- Icon and Network Info -->
                <div class="d-flex align-items-center gap-3">
                    <i class="{{ link.icon_class }} fs-2"></i>
                    <div class="d-flex flex-column">
                        <h5 class="card-title mb-0" style="color: {{ link.text_color }}; font-weight: bold;">
                            {{ link.name }}
                        </h5>
                        <small style="color: {{ link.text_color }}; opacity: 0.85;">
                            @{{ link.handle }}
                        </small>
                    </div>
                </div>

                <!-- Call to Action Button -->
                <a href="{{ link.url }}" class="btn btn-sm px-3"
                   style="background-color: {{ link.text_color }};
                          color: {{ link.bg_color }};
                          border-radius: 20px;
                          font-weight: 600;"
                   target="_blank" rel="noopener noreferrer">
                    {{ link.cta }}
                </a>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
"""

# 3. Render and display the template in the notebook
jinja_template = Template(template_string)
html_output = jinja_template.render(links=social_links)

display(HTML(html_output))

raw_networks = """500px, Bandcamp, ebay, Lookbook, Medium, SoundCloud, Steam, Unsplash, Untappd, VSCO, Airbnb, ArtStation, Behance, Chictopia, Crunchbase, Depop, DeviantArt, ESPN, EyeEm, Fitbit, Flickr, Goodreads, Mixcloud, MyFitnessPal, Nike Run Club, Pexels, PlayStation Network, Product Hunt, Quora, Reddit, SlideShare, Spotify, Strava, TripAdvisor, Twitch, Vimeo, Xbox Live"""

# Some known bootstrap icons and brand colors for the list
brand_data = {
    "Medium": {"icon": "bi bi-medium", "bg": "#000000", "text": "#ffffff"},
    "Reddit": {"icon": "bi bi-reddit", "bg": "#FF4500", "text": "#ffffff"},
    "Spotify": {"icon": "bi bi-spotify", "bg": "#1DB954", "text": "#ffffff"},
    "Twitch": {"icon": "bi bi-twitch", "bg": "#9146FF", "text": "#ffffff"},
    "Vimeo": {"icon": "bi bi-vimeo", "bg": "#1AB7EA", "text": "#ffffff"},
    "Steam": {"icon": "bi bi-steam", "bg": "#171a21", "text": "#ffffff"},
    "Strava": {"icon": "bi bi-strava", "bg": "#FC4C02", "text": "#ffffff"},
    "Behance": {"icon": "bi bi-behance", "bg": "#1769ff", "text": "#ffffff"},
    "Quora": {"icon": "bi bi-quora", "bg": "#b92b27", "text": "#ffffff"},
    "PlayStation Network": {"icon": "bi bi-playstation", "bg": "#003791", "text": "#ffffff"},
    "Xbox Live": {"icon": "bi bi-xbox", "bg": "#107C10", "text": "#ffffff"},
}

new_links = []
for name in raw_networks.split(','):
    name = name.strip()
    if not name:
        continue

    # Default styling for networks without a specific match
    data = brand_data.get(name, {"icon": "bi bi-link-45deg", "bg": "#f8f9fa", "text": "#212529"})

    # Create a placeholder URL and handle based on the name
    base_url = name.lower().replace(" ", "")

    new_links.append({
        "name": name,
        "url": f"https://{base_url}.com/{base_url}_user",
        "profile_pattern": f"https://{base_url}.com/{{handle}}",
        "handle": f"{base_url}_user",
        "icon_class": data["icon"],
        "bg_color": data["bg"],
        "text_color": data["text"],
        "border_color": data["text"], # matching border to text color for contrast
        "cta": "Visit"
    })

# Append to our existing list
# (Avoids duplicating if cell is run multiple times)
existing_names = {link['name'] for link in social_links}
for link in new_links:
    if link['name'] not in existing_names:
        social_links.append(link)

# Re-render the HTML template with the expanded list
html_output = jinja_template.render(links=social_links)
display(HTML(html_output))

# 1. Update User Profile Data Structure with Skills, Adult Flag, Intro Video, and GA4 ID
user_profile = {
    "avatar_url": "https://ui-avatars.com/api/?name=Jane+Doe&background=0D8ABC&color=fff&size=128",
    "display_name": "Jane Doe",
    "handle": "@janedoe",
    "bio": "Software Engineer | Content Creator | Coffee Enthusiast",
    "location": "San Francisco, CA",
    "bg_color": "#f4f6f8",
    "bg_image_url": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=500&auto=format&fit=crop",
    "text_color": "#333333",
    "skills": ["Python", "Flask", "UI/UX", "Gaming"], # NEW: Skill Badges
    "is_adult_oriented": True, # NEW: Adult profile flag
    "intro_video": { # NEW: Intro Video
        "platform": "youtube", # Options: 'youtube' or 'vimeo'
        "video_id": "dQw4w9WgXcQ" # Example YouTube ID
    },
    "ga4_id": "G-ABC123XYZ9" # NEW: User's personal Google Analytics 4 ID
}

# 2. Enrich Social Links (Mocking Categories, Pinned status, and optional UTMs)
for link in social_links:
    # Assign Mock Categories based on name
    if link['name'] in ['GitHub', 'GitLab', 'Steam', 'Xbox Live', 'PlayStation Network']:
        link['category'] = 'Gaming & Dev'
    elif link['name'] in ['YouTube', 'Twitch', 'Vimeo', 'Medium', 'Spotify']:
        link['category'] = 'Content'
    elif link['name'] in ['Twitter / X', 'LinkedIn', 'Reddit', 'Quora']:
        link['category'] = 'Social'
    else:
        link['category'] = 'Other'

    # Mock Pin (Let's pin GitHub to show the primary property)
    link['is_pinned'] = (link['name'] == 'GitHub')

    # Mock Optional UTM Code (added to the pinned link as an example)
    if link['is_pinned']:
        link['utm_params'] = "?utm_source=my_profile_page&utm_medium=referral"
    else:
        link['utm_params'] = "" # Keep it clean if no UTM is provided

# Group links for Jinja processing
pinned_links = [l for l in social_links if l.get('is_pinned')]
categorized_links = {}
for l in social_links:
    if not l.get('is_pinned'):
        categorized_links.setdefault(l['category'], []).append(l)

# 3. Updated Jinja2 Template combining Profile Header + Intro Video + Social Links + Tabs + Modal + Footer + GA4
combined_template_string = """
<!-- Include Bootstrap CSS, JS & Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

{% if profile.ga4_id %}
<!-- Google tag (gtag.js) - User's Custom GA4 Tracking -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ profile.ga4_id }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{ profile.ga4_id }}');
</script>
{% endif %}

<main class="container mt-5 mb-2" style="max-width: 500px;" aria-label="{{ profile.display_name }}'s Linktree Profile">

    <!-- === PROFILE HEADER CARD === -->
    <section class="card shadow-sm mb-4 border-0"
         style="background-color: {{ profile.bg_color }};
                {% if profile.bg_image_url %}
                background-image: url('{{ profile.bg_image_url }}');
                background-size: cover;
                background-position: center;
                {% endif %}
                border-radius: 20px;
                position: relative; overflow: hidden;"
         aria-labelledby="profile-name">

        {% if profile.is_adult_oriented %}
        <!-- Adult Content Ribbon -->
        <div aria-label="18+ Adult Content Warning" style="position: absolute; top: 0; right: 0; overflow: hidden; width: 120px; height: 120px; z-index: 10;">
            <div style="position: absolute; top: 22px; right: -32px; width: 140px; background-color: #dc3545; color: #fff; text-align: center; font-size: 0.75rem; font-weight: bold; padding: 4px 0; transform: rotate(45deg); box-shadow: 0 2px 4px rgba(0,0,0,0.3); letter-spacing: 1px;">
                18+ ADULT
            </div>
        </div>
        {% endif %}

        <div class="card-body text-center p-4">
            <!-- Avatar -->
            <img src="{{ profile.avatar_url }}" alt="Profile avatar of {{ profile.display_name }}"
                 class="rounded-circle mb-3 shadow-sm"
                 style="width: 110px; height: 110px; object-fit: cover; border: 4px solid #ffffff;">

            <!-- User Info -->
            <h3 id="profile-name" class="card-title fw-bold mb-0" style="color: {{ profile.text_color }};">
                {{ profile.display_name }}
            </h3>
            <p class="mb-3" style="color: {{ profile.text_color }}; opacity: 0.7;" aria-label="User Handle">
                {{ profile.handle }}
            </p>

            {% if profile.bio %}
            <p class="card-text mb-2" style="color: {{ profile.text_color }};">
                {{ profile.bio }}
            </p>
            {% endif %}

            <!-- Skill Badges -->
            {% if profile.skills %}
            <div class="d-flex flex-wrap justify-content-center gap-2 mb-3" aria-label="Skills">
                {% for skill in profile.skills %}
                <span class="badge rounded-pill" style="background-color: {{ profile.text_color }}; color: {{ profile.bg_color }}; opacity: 0.8;">
                    {{ skill }}
                </span>
                {% endfor %}
            </div>
            {% endif %}

            {% if profile.location %}
            <div class="d-flex justify-content-center align-items-center gap-1 mb-3" style="color: {{ profile.text_color }}; opacity: 0.8;" aria-label="Location: {{ profile.location }}">
                <i class="bi bi-geo-alt-fill" aria-hidden="true"></i>
                <small>{{ profile.location }}</small>
            </div>
            {% endif %}

            <!-- Contact Modal Trigger -->
            <button type="button" class="btn btn-sm px-4 rounded-pill fw-bold"
                    style="background-color: {{ profile.text_color }}; color: {{ profile.bg_color }};"
                    data-bs-toggle="modal" data-bs-target="#contactModal"
                    aria-label="Contact {{ profile.display_name }}" aria-haspopup="dialog">
                <i class="bi bi-envelope-fill me-2" aria-hidden="true"></i>Contact Me
            </button>
        </div>
    </section>

    <!-- === INTRO VIDEO SECTION === -->
    {% if profile.intro_video %}
    <section class="card shadow-sm mb-4 border-0" style="border-radius: 20px; overflow: hidden; background-color: {{ profile.bg_color }};" aria-label="Introduction Video">
        <div class="card-body p-0">
            <div class="ratio ratio-16x9">
                {% if profile.intro_video.platform == 'youtube' %}
                <iframe src="https://www.youtube.com/embed/{{ profile.intro_video.video_id }}" title="{{ profile.display_name }}'s YouTube intro video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                {% elif profile.intro_video.platform == 'vimeo' %}
                <iframe src="https://player.vimeo.com/video/{{ profile.intro_video.video_id }}" title="{{ profile.display_name }}'s Vimeo intro video" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
                {% endif %}
            </div>
        </div>
    </section>
    {% endif %}

    <!-- === PINNED LINKS SECTION === -->
    {% if pinned_links %}
    <section class="mb-4" aria-labelledby="pinned-links-heading">
        <h6 id="pinned-links-heading" class="text-uppercase text-muted fw-bold mb-3 ms-2" style="font-size: 0.85rem;">
            <i class="bi bi-pin-angle-fill me-2" aria-hidden="true"></i>Pinned
        </h6>
        <div class="d-flex flex-column gap-3">
            {% for link in pinned_links %}
            <article class="card shadow transition-all"
                 style="background-color: {{ link.bg_color }};
                        border: 3px solid #ffc107;
                        color: {{ link.text_color }};
                        border-radius: 15px;">
                <div class="card-body d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center gap-3">
                        <i class="{{ link.icon_class }} fs-2" aria-hidden="true"></i>
                        <div class="d-flex flex-column">
                            <h5 class="card-title mb-0 fw-bold">{{ link.name }}</h5>
                            <small style="opacity: 0.85;">@{{ link.handle }}</small>
                        </div>
                    </div>
                    <a href="{{ link.url }}{{ link.utm_params }}" class="btn btn-sm px-3"
                       style="background-color: {{ link.text_color }}; color: {{ link.bg_color }}; border-radius: 20px; font-weight: 600;"
                       target="_blank" rel="noopener noreferrer" aria-label="{{ link.cta }} on {{ link.name }}">{{ link.cta }}</a>
                </div>
            </article>
            {% endfor %}
        </div>
    </section>
    {% endif %}

    <!-- === TABBED SOCIAL CATEGORIES === -->
    <nav aria-label="Social Links Categories">
        <ul class="nav nav-pills nav-fill mb-3 gap-2" id="pills-tab" role="tablist">
            {% for category, links in categorized_links.items() %}
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if loop.first %}active{% endif %} rounded-pill fw-bold"
                        id="pills-{{ loop.index }}-tab"
                        data-bs-toggle="pill"
                        data-bs-target="#pills-{{ loop.index }}"
                        type="button"
                        role="tab"
                        aria-controls="pills-{{ loop.index }}"
                        aria-selected="{% if loop.first %}true{% else %}false{% endif %}"
                        style="border: 1px solid #dee2e6;">
                    {{ category }}
                </button>
            </li>
            {% endfor %}
        </ul>
    </nav>

    <div class="tab-content" id="pills-tabContent">
        {% for category, cat_links in categorized_links.items() %}
        <div class="tab-pane fade {% if loop.first %}show active{% endif %}"
             id="pills-{{ loop.index }}"
             role="tabpanel"
             aria-labelledby="pills-{{ loop.index }}-tab"
             tabindex="0">
            <div class="d-flex flex-column gap-3">
                {% for link in cat_links %}
                <article class="card shadow-sm transition-all"
                     style="background-color: {{ link.bg_color }};
                            border: 2px solid {{ link.border_color }};
                            color: {{ link.text_color }};
                            border-radius: 15px;">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div class="d-flex align-items-center gap-3">
                            <i class="{{ link.icon_class }} fs-2" aria-hidden="true"></i>
                            <div class="d-flex flex-column">
                                <h5 class="card-title mb-0 fw-bold">{{ link.name }}</h5>
                                <small style="opacity: 0.85;">@{{ link.handle }}</small>
                            </div>
                        </div>
                        <a href="{{ link.url }}{{ link.utm_params }}" class="btn btn-sm px-3"
                           style="background-color: {{ link.text_color }}; color: {{ link.bg_color }}; border-radius: 20px; font-weight: 600;"
                           target="_blank" rel="noopener noreferrer" aria-label="{{ link.cta }} on {{ link.name }}">{{ link.cta }}</a>
                    </div>
                </article>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- === FOOTER === -->
    <footer class="mt-5 mb-3 text-center" role="contentinfo">
        <div class="d-flex justify-content-center gap-3 mb-2" style="font-size: 0.85rem;">
            <a href="/terms" class="text-decoration-none fw-semibold" style="color: {{ profile.text_color }}; opacity: 0.7;" aria-label="Terms of Service">Terms</a>
            <a href="/privacy" class="text-decoration-none fw-semibold" style="color: {{ profile.text_color }}; opacity: 0.7;" aria-label="Privacy Policy">Privacy</a>
            <a href="/report" class="text-decoration-none fw-semibold text-danger" style="opacity: 0.8;" aria-label="Report Abuse">Report Abuse</a>
        </div>
        <small style="color: {{ profile.text_color }}; opacity: 0.5;">
            Powered by <strong>FlaskTree</strong>
        </small>
    </footer>

</main>

<!-- === CONTACT MODAL === -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" style="border-radius: 15px;">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold" id="contactModalLabel">Message {{ profile.display_name }}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close modal"></button>
      </div>
      <div class="modal-body">
        <form action="/submit-contact" method="POST">
          <div class="mb-3">
            <label for="senderName" class="form-label fw-semibold">Your Name</label>
            <input type="text" class="form-control bg-light" id="senderName" name="name" required aria-required="true">
          </div>
          <div class="mb-3">
            <label for="senderEmail" class="form-label fw-semibold">Your Email</label>
            <input type="email" class="form-control bg-light" id="senderEmail" name="email" required aria-required="true">
          </div>
          <div class="mb-4">
            <label for="messageText" class="form-label fw-semibold">Message</label>
            <textarea class="form-control bg-light" id="messageText" name="message" rows="4" required aria-required="true"></textarea>
          </div>
          <button type="submit" class="btn w-100 rounded-pill fw-bold py-2"
                  style="background-color: {{ profile.text_color }}; color: {{ profile.bg_color }};">
            Send Message
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
"""

# 4. Render and display the combined template
combined_jinja_template = Template(combined_template_string)
final_html_output = combined_jinja_template.render(
    profile=user_profile,
    pinned_links=pinned_links,
    categorized_links=categorized_links
)

display(HTML(final_html_output))

from jinja2 import Template
from IPython.display import display, HTML

# A Bootstrap 5 Navbar template meant for your Flask base.html
navbar_template = """
<!-- Bootstrap CSS (Ensure this is in your base template's <head>) -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <!-- Brand Logo -->
    <a class="navbar-brand fw-bold d-flex align-items-center gap-2 text-dark" href="/">
        <i class="bi bi-tree-fill text-success fs-4"></i> FlaskTree
    </a>

    <!-- Mobile Toggle Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Nav Links -->
    <div class="collapse navbar-collapse" id="mainNavbar">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/discover">Discover</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/pricing">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/help">Help / FAQ</a>
        </li>
      </ul>

      <!-- Auth Links (Right Aligned) -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex align-items-lg-center gap-2">

        <!-- Jinja2 logic simulating Flask-Login's current_user.is_authenticated -->
        {% if is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="/dashboard"><i class="bi bi-speedometer2 me-1"></i>Dashboard</a></li>
            <li class="nav-item"><a class="nav-link" href="/analytics"><i class="bi bi-graph-up me-1"></i>Analytics</a></li>
            <li class="nav-item"><a class="nav-link" href="/settings"><i class="bi bi-gear me-1"></i>Settings</a></li>
            <li class="nav-item mt-2 mt-lg-0">
                <a class="btn btn-outline-dark btn-sm rounded-pill px-3" href="/logout">Logout</a>
            </li>
        {% else %}
            <li class="nav-item"><a class="nav-link fw-semibold" href="/login">Log in</a></li>
            <li class="nav-item mt-2 mt-lg-0">
                <a class="btn btn-success btn-sm rounded-pill px-4 fw-bold shadow-sm" href="/register">Sign up free</a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
"""

# Compile the template
jinja_nav = Template(navbar_template)

# Display how the navbar looks for a standard visitor (Logged Out)
display(HTML("<div class='p-3 mb-2 bg-light text-dark fw-bold rounded'>1. Logged-Out Visitor View (Landing Page)</div>"))
display(HTML(jinja_nav.render(is_authenticated=False)))

# Display how the navbar looks for an active user (Logged In)
display(HTML("<div class='p-3 mt-4 mb-2 bg-light text-dark fw-bold rounded'>2. Logged-In User View (Dashboard Access)</div>"))
display(HTML(jinja_nav.render(is_authenticated=True)))


# --- NEW: Help / FAQ Section ---
faq_data = [
    {
        "question": "How can I maximize my profile's visibility?",
        "answer": "Add your FlaskTree link to all your social media bios (Instagram, Twitter, TikTok, LinkedIn). The more places you share it, the more visibility you'll get! Don't forget to mention it in your posts and videos."
    },
    {
        "question": "Does adding a custom GA4 ID help?",
        "answer": "Yes! While it doesn't directly boost traffic, adding your Google Analytics 4 ID helps you understand where your audience is coming from, which links they click the most, and what times they are most active. You can use this data to focus on the best channels."
    },
    {
        "question": "Why should I pin a link?",
        "answer": "Pinning a link highlights it at the top of your profile with a special border, making it the first thing visitors see. Use this for your most important content, newest video, or a current campaign you want to drive traffic to."
    },
    {
        "question": "How do UTM parameters work?",
        "answer": "UTM parameters allow you to track exactly which link on your FlaskTree profile is driving traffic to your external sites. We support adding custom UTMs to your links in the dashboard, giving you deeper insights in your analytics software."
    }
]

faq_template = """
<div class="container py-5 mt-4" style="max-width: 800px;">
    <div class="text-center mb-5">
        <h2 class="fw-bold"><i class="bi bi-question-circle text-success me-2"></i>Help & FAQ</h2>
        <p class="text-muted">Learn how to get the most out of your FlaskTree profile.</p>
    </div>

    <div class="accordion shadow-sm rounded-4" id="faqAccordion">
        {% for item in faqs %}
        <div class="accordion-item border-0 border-bottom">
            <h2 class="accordion-header" id="heading{{ loop.index }}">
                <button class="accordion-button {% if not loop.first %}collapsed{% endif %} fw-bold bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ loop.index }}" aria-expanded="{% if loop.first %}true{% else %}false{% endif %}" aria-controls="collapse{{ loop.index }}">
                    {{ item.question }}
                </button>
            </h2>
            <div id="collapse{{ loop.index }}" class="accordion-collapse collapse {% if loop.first %}show{% endif %}" aria-labelledby="heading{{ loop.index }}" data-bs-parent="#faqAccordion">
                <div class="accordion-body text-muted">
                    {{ item.answer }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="text-center mt-5">
        <p class="text-muted">Still need help?</p>
        <a href="mailto:support@flasktree.com" class="btn btn-outline-dark rounded-pill px-4 fw-bold">Contact Support</a>
    </div>
</div>
"""

jinja_faq = Template(faq_template)
display(HTML("<div class='p-3 mt-5 mb-2 bg-light text-dark fw-bold rounded'>3. Help / FAQ Page</div>"))
display(HTML(jinja_faq.render(faqs=faq_data)))

from jinja2 import Template
from IPython.display import display, HTML

# Mock support categories with "instant answers" to deflect tickets
support_categories = [
    {
        "value": "billing",
        "label": "Billing & Subscriptions",
        "hint": "💡 <strong>Instant Answer:</strong> You can update your payment method and download invoices directly from the <a href='/billing' class='alert-link'>Billing Dashboard</a>."
    },
    {
        "value": "access",
        "label": "Login & Account Access",
        "hint": "💡 <strong>Instant Answer:</strong> Forgot your password? You can reset it instantly using the <a href='/reset-password' class='alert-link'>Password Reset tool</a>."
    },
    {
        "value": "technical",
        "label": "Technical Issue or Bug",
        "hint": "💡 <strong>Instant Answer:</strong> Please try clearing your browser cache first. If the issue persists, please let us know your browser and device below."
    },
    {
        "value": "feature",
        "label": "Feature Request",
        "hint": "💡 <strong>Instant Answer:</strong> We love new ideas! Check our <a href='/roadmap' class='alert-link'>Public Roadmap</a> to see if it's already planned."
    },
    {
        "value": "other",
        "label": "Other Inquiry",
        "hint": ""
    }
]

support_template = """
<!-- Bootstrap CSS & Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<div class="container py-5 mt-4" style="max-width: 700px;">
    <div class="card shadow border-0 rounded-4 p-4 p-md-5">
        <div class="text-center mb-4">
            <h2 class="fw-bold"><i class="bi bi-headset text-primary me-2"></i>Contact Support</h2>
            <p class="text-muted">We're here to help! Please fill out the form below.</p>
        </div>

        <form action="/submit-support" method="POST">
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="userName" class="form-label fw-semibold">Name</label>
                    <input type="text" class="form-control bg-light" id="userName" name="name" required placeholder="Jane Doe">
                </div>
                <div class="col-md-6">
                    <label for="userEmail" class="form-label fw-semibold">Email</label>
                    <input type="email" class="form-control bg-light" id="userEmail" name="email" required placeholder="jane@example.com">
                </div>

                <div class="col-12">
                    <label for="supportType" class="form-label fw-semibold">How can we help you?</label>
                    <select class="form-select bg-light border-primary border-opacity-25" id="supportType" name="support_type" required onchange="showHint(this.value)">
                        <option value="" disabled selected>Select an option...</option>
                        {% for cat in categories %}
                            <option value="{{ cat.value }}">{{ cat.label }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Deflection Hints Container (Hidden by default) -->
                <div class="col-12" id="hintContainer" style="display: none; transition: opacity 0.3s ease-in-out;">
                    <div class="alert alert-primary border-0 shadow-sm mb-0" role="alert">
                        <span id="hintText"></span>
                    </div>
                </div>

                <div class="col-12">
                    <label for="messageSubject" class="form-label fw-semibold">Subject</label>
                    <input type="text" class="form-control bg-light" id="messageSubject" name="subject" required placeholder="Brief summary of your issue">
                </div>

                <div class="col-12">
                    <label for="messageBody" class="form-label fw-semibold">Message</label>
                    <textarea class="form-control bg-light" id="messageBody" name="message" rows="5" required placeholder="Please provide as much detail as possible..."></textarea>
                </div>

                <div class="col-12 mt-4">
                    <button type="submit" class="btn btn-primary w-100 rounded-pill fw-bold py-2 shadow-sm">
                        <i class="bi bi-send-fill me-2"></i>Submit Support Request
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- JavaScript to handle showing hints based on the dropdown selection -->
<script>
    // Pass our Jinja data into a JS object safely
    const hints = {
        {% for cat in categories %}
            "{{ cat.value }}": `{{ cat.hint | safe }}`,
        {% endfor %}
    };

    function showHint(selectedValue) {
        const hintContainer = document.getElementById('hintContainer');
        const hintText = document.getElementById('hintText');
        const hint = hints[selectedValue];

        if (hint && hint.trim() !== '') {
            hintText.innerHTML = hint;
            hintContainer.style.display = 'block';
        } else {
            hintContainer.style.display = 'none';
        }
    }
</script>
"""

jinja_support = Template(support_template)
display(HTML("<div class='p-3 mt-5 mb-2 bg-light text-dark fw-bold rounded'>4. Support Contact Form (with Ticket Deflection)</div>"))
display(HTML(jinja_support.render(categories=support_categories)))

from jinja2 import Template
from IPython.display import display, HTML

# Mock data for the dashboard
dashboard_data = {
    "user": {
        "name": "Jane Doe",
        "email": "jane@example.com",
        "avatar": "https://ui-avatars.com/api/?name=Jane+Doe&background=0D8ABC&color=fff",
        "live_url": "https://flasktree.com/janedoe"
    },
    "analytics": {
        "views": "1,248",
        "clicks": "392",
        "ctr": "31.4%"
    }
}

dashboard_template = """
<!-- Bootstrap CSS & Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<div class="container-fluid bg-light min-vh-100 py-4">
    <div class="container">
        <div class="row g-4">

            <!-- === SIDEBAR === -->
            <div class="col-lg-3">
                <div class="card border-0 shadow-sm rounded-4 mb-4">
                    <div class="card-body text-center">
                        <img src="{{ data.user.avatar }}" class="rounded-circle mb-3 shadow-sm" style="width: 80px; height: 80px; object-fit: cover;">
                        <h5 class="fw-bold mb-1">{{ data.user.name }}</h5>
                        <p class="text-muted small mb-3">{{ data.user.email }}</p>
                        <a href="{{ data.user.live_url }}" target="_blank" class="btn btn-outline-success btn-sm rounded-pill w-100 fw-bold">
                            <i class="bi bi-box-arrow-up-right me-1"></i> View Live Page
                        </a>
                    </div>
                </div>

                <div class="list-group shadow-sm rounded-4 border-0">
                    <a href="#" class="list-group-item list-group-item-action active fw-semibold py-3 border-0">
                        <i class="bi bi-speedometer2 me-2"></i> Dashboard
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0">
                        <i class="bi bi-link-45deg me-2"></i> Manage Links
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0">
                        <i class="bi bi-person-badge me-2"></i> Profile Info
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0">
                        <i class="bi bi-palette me-2"></i> Appearance
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0">
                        <i class="bi bi-graph-up me-2"></i> Analytics
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0">
                        <i class="bi bi-credit-card me-2"></i> Billing
                    </a>
                    <a href="#" class="list-group-item list-group-item-action fw-semibold py-3 border-0 text-danger">
                        <i class="bi bi-box-arrow-right me-2"></i> Log Out
                    </a>
                </div>
            </div>

            <!-- === MAIN CONTENT === -->
            <div class="col-lg-9">
                <h3 class="fw-bold mb-4">Welcome back, {{ data.user.name.split(' ')[0] }}! ✨</h3>

                <!-- Analytics Row -->
                <h5 class="fw-semibold mb-3">At a Glance</h5>
                <div class="row g-3 mb-5">
                    <div class="col-md-4">
                        <div class="card border-0 shadow-sm rounded-4 h-100">
                            <div class="card-body d-flex flex-column justify-content-center">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <span class="text-muted fw-semibold">Total Views</span>
                                    <div class="bg-primary bg-opacity-10 text-primary p-2 rounded-3">
                                        <i class="bi bi-eye fs-5"></i>
                                    </div>
                                </div>
                                <h2 class="fw-bold mb-0">{{ data.analytics.views }}</h2>
                                <small class="text-success fw-semibold"><i class="bi bi-arrow-up-short"></i> 12% this week</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-0 shadow-sm rounded-4 h-100">
                            <div class="card-body d-flex flex-column justify-content-center">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <span class="text-muted fw-semibold">Link Clicks</span>
                                    <div class="bg-success bg-opacity-10 text-success p-2 rounded-3">
                                        <i class="bi bi-hand-index-thumb fs-5"></i>
                                    </div>
                                </div>
                                <h2 class="fw-bold mb-0">{{ data.analytics.clicks }}</h2>
                                <small class="text-success fw-semibold"><i class="bi bi-arrow-up-short"></i> 5% this week</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-0 shadow-sm rounded-4 h-100">
                            <div class="card-body d-flex flex-column justify-content-center">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <span class="text-muted fw-semibold">Avg. CTR</span>
                                    <div class="bg-warning bg-opacity-10 text-warning p-2 rounded-3">
                                        <i class="bi bi-lightning-charge fs-5"></i>
                                    </div>
                                </div>
                                <h2 class="fw-bold mb-0">{{ data.analytics.ctr }}</h2>
                                <small class="text-secondary fw-semibold">Steady</small>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Quick Actions -->
                <h5 class="fw-semibold mb-3">Quick Actions</h5>
                <div class="row g-3">
                    <div class="col-sm-6">
                        <a href="#" class="text-decoration-none">
                            <div class="card border-0 shadow-sm rounded-4 h-100 hover-card" style="transition: transform 0.2s;">
                                <div class="card-body d-flex align-items-center gap-3 p-4">
                                    <div class="bg-dark text-white p-3 rounded-circle d-flex align-items-center justify-content-center" style="width: 50px; height: 50px;">
                                        <i class="bi bi-plus-lg fs-4"></i>
                                    </div>
                                    <div>
                                        <h6 class="fw-bold mb-1 text-dark">Add New Link</h6>
                                        <small class="text-muted">Create a new redirect link</small>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <a href="#" class="text-decoration-none">
                            <div class="card border-0 shadow-sm rounded-4 h-100 hover-card" style="transition: transform 0.2s;">
                                <div class="card-body d-flex align-items-center gap-3 p-4">
                                    <div class="bg-info bg-opacity-10 text-info p-3 rounded-circle d-flex align-items-center justify-content-center" style="width: 50px; height: 50px;">
                                        <i class="bi bi-pencil-square fs-4"></i>
                                    </div>
                                    <div>
                                        <h6 class="fw-bold mb-1 text-dark">Edit Profile</h6>
                                        <small class="text-muted">Update your bio and avatar</small>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<style>
.hover-card:hover {
    transform: translateY(-3px);
    cursor: pointer;
}
</style>
"""

# Compile and display the template
jinja_dashboard = Template(dashboard_template)
display(HTML(jinja_dashboard.render(data=dashboard_data)))

from jinja2 import Template
from IPython.display import display, HTML

# 1. Mock Data for Public Profiles (Simulating a database query)
public_profiles = [
    {
        "username": "janedoe",
        "display_name": "Jane Doe",
        "avatar": "https://ui-avatars.com/api/?name=Jane+Doe&background=0D8ABC&color=fff",
        "bio": "Software Engineer | Content Creator | Coffee Enthusiast",
        "tags": ["Tech", "Vlogs"],
        "platforms": ["YouTube", "GitHub", "Twitter / X"]
    },
    {
        "username": "gamerkyle",
        "display_name": "Kyle Plays",
        "avatar": "https://ui-avatars.com/api/?name=Kyle+Plays&background=FF4500&color=fff",
        "bio": "Speedruns and indie game reviews. Live every Tuesday!",
        "tags": ["Gaming", "Reviews"],
        "platforms": ["Twitch", "YouTube", "Steam"]
    },
    {
        "username": "sarahwrites",
        "display_name": "Sarah's Blog",
        "avatar": "https://ui-avatars.com/api/?name=Sarah+W&background=17a2b8&color=fff",
        "bio": "Sharing my journey as a freelance writer.",
        "tags": ["Writing", "Lifestyle"],
        "platforms": ["Medium", "Twitter / X", "LinkedIn"]
    },
    {
        "username": "chefmike",
        "display_name": "Chef Mike",
        "avatar": "https://ui-avatars.com/api/?name=Chef+Mike&background=dc3545&color=fff",
        "bio": "Easy recipes for busy people. New videos weekly!",
        "tags": ["Food", "Tutorials"],
        "platforms": ["YouTube", "Instagram", "TikTok"]
    }
]

# 2. Filter profiles to only show users who have a YouTube link
youtube_creators = [profile for profile in public_profiles if "YouTube" in profile["platforms"]]

# NEW: Mock Pagination Data (Simulating Flask-SQLAlchemy Pagination)
pagination_data = {
    "current_page": 1,
    "total_pages": 24,
    "total_items": 473,
    "has_prev": False,
    "has_next": True,
    "prev_num": None,
    "next_num": 2,
    "iter_pages": [1, 2, 3, 4, 5, None, 24]
}

# 3. Jinja2 Template for the Discover Directory (Compact Horizontal Layout with Pagination)
directory_template = """
<!-- Bootstrap CSS, JS & Icons -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<div class="container py-5 bg-light rounded-4 my-4" style="max-width: 1000px;">
    <div class="text-center mb-4">
        <h2 class="fw-bold"><i class="bi bi-compass text-primary me-2"></i>Discover</h2>
        <p class="text-muted">Find and connect with amazing creators on FlaskTree.</p>
    </div>

    <!-- Section Header: YouTube Creators -->
    <div class="mb-4 d-flex align-items-center justify-content-between border-bottom pb-2">
        <h4 class="fw-bold mb-0">
            <i class="bi bi-youtube text-danger me-2"></i>Creators on YouTube
        </h4>
        <span class="badge bg-danger rounded-pill">{{ pagination.total_items }} Profiles</span>
    </div>

    <!-- Compact Horizontal Profile List -->
    <div class="d-flex flex-column gap-3">
        {% for profile in creators %}
        <div class="card border-0 shadow-sm rounded-4 hover-lift" style="transition: transform 0.2s;"
             data-bs-toggle="tooltip" data-bs-placement="top"
             title="About {{ profile.display_name }}: {{ profile.bio }}">
            <div class="card-body p-3 d-flex align-items-center flex-wrap flex-md-nowrap gap-3">
                <!-- Avatar -->
                <img src="{{ profile.avatar }}" alt="{{ profile.display_name }}"
                     class="rounded-circle shadow-sm flex-shrink-0"
                     style="width: 60px; height: 60px; object-fit: cover; border: 2px solid #f8f9fa;">

                <!-- Info -->
                <div class="flex-grow-1 min-w-0">
                    <div class="d-flex align-items-center gap-2 mb-1">
                        <h6 class="fw-bold mb-0 text-truncate">{{ profile.display_name }}</h6>
                        <small class="text-muted">@{{ profile.username }}</small>
                    </div>

                    <div class="d-flex flex-wrap gap-1">
                        {% for tag in profile.tags %}
                            <span class="badge bg-light text-dark border" style="font-size: 0.7rem;">{{ tag }}</span>
                        {% endfor %}
                    </div>
                </div>

                <!-- Actions -->
                <div class="d-flex align-items-center gap-4 ms-md-auto mt-3 mt-md-0 border-md-start ps-md-4 flex-shrink-0 w-100 w-md-auto justify-content-end">
                    <a href="/{{ profile.username }}" class="btn btn-sm btn-dark rounded-pill px-4 fw-semibold">
                        View
                    </a>
                </div>
            </div>
        </div>
        {% else %}
        <div class="text-center py-5">
            <p class="text-muted fs-5">No creators found matching this filter.</p>
        </div>
        {% endfor %}
    </div>

    <!-- NEW: Pagination Controls -->
    {% if pagination and pagination.total_pages > 1 %}
    <nav aria-label="Creator directory pagination" class="mt-5">
        <ul class="pagination justify-content-center mb-0">
            <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                <a class="page-link rounded-start-pill px-3" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {% for page_num in pagination.iter_pages %}
                {% if page_num %}
                    <li class="page-item {% if page_num == pagination.current_page %}active{% endif %}">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                <a class="page-link rounded-end-pill px-3" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>

<!-- Initialize Tooltips -->
<script>
    setTimeout(() => {
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    }, 200);
</script>

<style>
.hover-lift:hover {
    transform: translateY(-2px);
    box-shadow: 0 .25rem .75rem rgba(0,0,0,.1)!important;
    cursor: pointer;
}
.min-w-0 {
    min-width: 0;
}
@media (min-width: 768px) {
    .w-md-auto {
        width: auto !important;
    }
}
</style>
"""

# 4. Render and display
jinja_directory = Template(directory_template)
display(HTML(jinja_directory.render(creators=youtube_creators, pagination=pagination_data)))
