"""initial schema

Revision ID: 5ba675272b9b
Revises: 
Create Date: 2026-09-26 04:57:19.462282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba675272b9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('domains', sa.String(length=300), nullable=True),
    sa.Column('bg_color', sa.String(length=9), nullable=False),
    sa.Column('text_color', sa.String(length=9), nullable=False),
    sa.Column('border_color', sa.String(length=9), nullable=False),
    sa.Column('icon_code', sa.String(length=50), nullable=True),
    sa.Column('custom_icon_path', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.String(length=250), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('about_section', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_path', sa.String(length=300), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('tier_changed_at', sa.DateTime(), nullable=True),
    sa.Column('skills', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_adult_oriented', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('video_platform', sa.String(length=10), nullable=True),
    sa.Column('video_id', sa.String(length=64), nullable=True),
    sa.Column('ga4_id', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('contact_disabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_kind'), ['kind'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=80), nullable=False),
    sa.Column('sender_email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sender_ip', sa.String(length=45), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('icon_code', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('utm_params', sa.String(length=300), nullable=True),
    sa.Column('subhandle', sa.String(length=80), nullable=True),
    sa.Column('cta', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['link_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=60), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_dedupe_key'), ['dedupe_key'], unique=False)

    op.create_table('abuse_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_name', sa.String(length=80), nullable=True),
    sa.Column('reporter_email', sa.String(length=120), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('target_link_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abuse_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abuse_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_reports_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('link_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('is_broken', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('broken_since', sa.DateTime(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_check_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_check_results_is_broken'), ['is_broken'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_check_results_link_id'), ['link_id'], unique=True)

    op.create_table('message_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user')
    )
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_reads_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_reads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_reads_message_id'))

    op.drop_table('message_reads')
    with op.batch_alter_table('link_check_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_check_results_link_id'))
        batch_op.drop_index(batch_op.f('ix_link_check_results_is_broken'))

    op.drop_table('link_check_results')
    with op.batch_alter_table('abuse_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abuse_reports_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_abuse_reports_status'))
        batch_op.drop_index(batch_op.f('ix_abuse_reports_created_at'))

    op.drop_table('abuse_reports')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    op.drop_table('links')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_kind'))
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))

    op.drop_table('activity')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('link_sources')
    # ### end Alembic commands ###
